package com.ghuddy.backendapp.tours.es.repository;

import com.ghuddy.backendapp.tours.es.model.entities.ESTourComponentOptionCombinationDocument;
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;

import java.util.Optional;

public interface ESTourComponentOptionCombinationRepository extends ElasticsearchRepository<ESTourComponentOptionCombinationDocument, String> {
    Optional<ESTourComponentOptionCombinationDocument> findByAvailableTourPackageIdAndAccommodationOptionIdAndFoodOptionIdAndTransferOptionIdAndTransportationOptionIdAndGuideOptionIdAndSpotEntryOptionId(Long availableTourPackageId, Long accommodationOptionId, Long foodOptionId, Long transferOptionId, Long transportationOptionId, Long guideOptionId, Long spotEntryOptionId);

}
